Doc: update the README guidelines to recent changes
ansys/pyansys-cheat-sheet pull request #39
Opened 2023-06-14 13:32 UTC by Revathyvenugopal162

- [x] Update the readme with recent changes.
- [x] Update the layout of readme screenshots.

2023-06-14 14:08 UTC, RobPasMue commented on README.rst
> +   This command uses latexmk to compile your TeX file into a PDF.
```suggestion
   Here, replace ``<your_project>``, ``<your_folder_name>``, and ``<your_tex_file_name>`` with your actual project name, folder name, and TeX file name, respectively.
   This command uses latexmk to compile your TeX file into a PDF.
```

2023-06-14 14:08 UTC, RobPasMue commented on README.rst
> +   Here, replace <your_project>, <your_folder_name>, and <your_tex_file_name> with your actual project name, folder name, and TeX file name, respectively.
```suggestion
   Here, replace ``<your_project>``, ``<your_folder_name>``, and ``<your_tex_file_name>`` with your actual project name, folder name, and TeX file name, respectively.
```

2023-06-14 15:15 UTC, RobPasMue commented on README.rst
> +
The rendering of this table is not great. Please work on it so that they have a similar distribution

2023-06-14 15:16 UTC, RobPasMue requested changes
Apart from my comment, I think that's all. I don't think it's necessary to include them in the main README... I would just put the links to the cheat sheats. You are already showing the preview in the actual docs site. Let's keep the README simple

2023-06-14 15:20 UTC, Revathyvenugopal162 commented
Thats true.I think i added it adapted from matplotlib, as there was a request to keep https://github.com/matplotlib/cheatsheets aligned with this cheatsheets. Also as an examples to others how to add this. I am open to change this honestly.

2023-06-14 15:39 UTC, RobPasMue commented
> Thats true.I think i added it adapted from matplotlib, as there was a request to keep https://github.com/matplotlib/cheatsheets aligned with this cheatsheets. Also as an examples to others how to add this. I am open to change this honestly.

Yeah but they do not have a dedicated site where they put their cheat sheets AFAIK. So... I'd either remove them or properly format the tables. Up to you

2023-06-15 06:18 UTC, RobPasMue commented
Add PyDPF Core cheat sheet whenever you can @Revathyvenugopal162 and let's clean up this PR according to our messages.

2023-06-15 07:03 UTC, Revathyvenugopal162 commented
In that case we can keep the readme simple.

2023-06-15 07:09 UTC, RobPasMue approved these changes

2023-06-15 07:09 UTC, merged